CREATE DATABASE QLBH
GO
USE QLBH
CREATE TABLE VATTU
(MaVTu CHAR(4) NOT NULL PRIMARY KEY,
TenVTu VARCHAR(100) NOT NULL unique,
DvTinh VARCHAR(10)  NULL,
PhanTram REAL CHECK(Phantram between 0 and 100)
) 

CREATE TABLE NHACC
(MaNhaCc CHAR(3) NOT NULL PRIMARY KEY,
TenNhaCc VARCHAR(100) NOT NULL,
DiaChi VARCHAR(200) NOT NULL,
DienThoai VARCHAR(20) NULL
)

CREATE TABLE DONDH
(SoDh CHAR(4) NOT NULL PRIMARY KEY,
NgayDh DATETIME DEFAULT GETDATE(),
MaNhaCc CHAR(3) NOT NULL 
)

CREATE TABLE CTDONDH
(SoDh CHAR(4) NOT NULL FOREIGN KEY REFERENCES DONDH(SoDh),
MaVTu CHAR(4) NOT NULL FOREIGN KEY REFERENCES VATTU(MaVTu),
SlDat INT NOT NULL CHECK(SlDat >0))

CREATE TABLE PNHAP
(SoPn CHAR(4) PRIMARY KEY,
NgayNhap DATETIME ,
SoDh CHAR(4) NOT NULL)

CREATE TABLE CTPNHAP
(SoPn CHAR(4) FOREIGN KEY REFERENCES PNHAP(SoPn),
MaVTu CHAR(4) NOT NULL FOREIGN KEY REFERENCES VATTU(MaVTu),
SlNhap INT NOT NULL CHECK(SlNhap >0),
DgNhap MONEY NOT NULL CHECK(DgNhap >0)
)
CREATE TABLE PXUAT
(SoPx CHAR(4) NOT NULL PRIMARY KEY,
NgayXuat DATETIME ,
TenKh VARCHAR(100) NOT NULL)

CREATE TABLE CTPXUAT
(SoPx CHAR(4) FOREIGN KEY REFERENCES PXUAT(SoPx),
MaVTu CHAR(4) NOT NULL FOREIGN KEY REFERENCES VATTU(MaVTu),
SlXuat INT NOT NULL CHECK(SlXuat >0),
DgXuat MONEY NOT NULL CHECK(DgXuat >0))

CREATE TABLE TONKHO
(NamThang CHAR(10) NOT NULL PRIMARY KEY,
MaVTu CHAR(4) NOT NULL FOREIGN KEY REFERENCES VATTU(MaVTu),
SLDau INT NOT NULL CHECK(SLDau>0),
TongSLN INT NOT NULL CHECK(TongSLN>0),
TongSLX INT NOT NULL CHECK(TongSLX>0),
SLCuoi INT NOT NULL CHECK(SLCuoi>0),
)


INSERT INTO NHACC(MaNhaCc,TenNhaCc,DiaChi,DienThoai)
VALUES
('C01',N'Lê Minh Thành','54, Kim Mã,Cầu Giấy, Hà Nội','0781024'),
('C02',N'Trần Quang Anh','154, Hùng Vương,Hải Dương','7698154')
SELECT * FROM NHACC
GO

INSERT INTO VATTU(MaVTu,TenVTu,DvTinh,PhanTram)
VALUES 
('DD01','DVD hitachi 1 dia','Bộ',40)
SELECT * FROM VATTU
GO

INSERT INTO DONDH(SoDh,NgayDh,MaNhaCc)
VALUES
('D001',01/15/1012,'C01')
SELECT *FROM DONDH
GO 

INSERT INTO PNHAP(SoPn,NgayNhap,SoDh)
VALUES
('N001',01/17/2017,'D001')
SELECT *FROM PNHAP
GO

INSERT INTO CTDONDH(SoDh,MaVTu,SlDat)
VALUES
('D001','DD01',10)
SELECT * FROM CTDONDH
GO

INSERT INTO CTPNHAP(SoPn,MaVTu,SlNhap,DgNhap)
VALUES
('N001','DD01',8,250000)
SELECT * FROM CTDONDH
GO

INSERT INTO PXUAT(SoPx,NgayXuat,TenKh)
VALUES
('X001',01/17/2012,N'Nguyễn Ngọc Phương Nhi')
SELECT * FROM PXUAT
GO

INSERT INTO CTPXUAT(SoPx,MaVTu,SlXuat,DgXuat)
VALUES 
('X001','DD01',2,3500000)
SELECT * FROM CTPXUAT
GO

INSERT INTO TONKHO(NamThang,MaVTu,SLDau,TongSLN,TongSLX,SLCuoi)
VALUES
('201201','DD01',1,10,6,4)
SELECT * FROM TONKHO
GO

