
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manage-student
    username: root
    password: "041103"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  banner:
    location: classpath:a.txt